/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_fernandogoti;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando Goti
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Crear_Usuarios = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tex_edad_cuenta = new javax.swing.JTextField();
        tex_nombre_cuenta = new javax.swing.JTextField();
        tex_user_cuenta = new javax.swing.JTextField();
        tex_password_cuenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bguardar_cuenta = new javax.swing.JButton();
        crear_Canciones = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        tex_nombre_canciones = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tex_artistas_canciones = new javax.swing.JTextField();
        tex_duracion_canciones = new javax.swing.JTextField();
        tex_genero_cancion = new javax.swing.JTextField();
        bguardar_cancion = new javax.swing.JButton();
        Crear_Playlist = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        tex_nombreplaylist = new javax.swing.JTextField();
        guardar_playlist = new javax.swing.JButton();
        iniciar_sesion = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tex_usuario_login = new javax.swing.JTextField();
        biiniciar_sesion = new javax.swing.JButton();
        tex_clave_login = new javax.swing.JPasswordField();
        Menu_crearalbum = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tex_nombrealbum = new javax.swing.JTextField();
        tex_artista = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_crearcuenta = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_crearcancion = new javax.swing.JMenuItem();
        menu_crearplaylist = new javax.swing.JMenuItem();
        menu_salir = new javax.swing.JMenuItem();
        menu_iniciar_sesion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel1.setText("Nombre:");

        jLabel2.setText("Edad:");

        jLabel3.setText("UserName:");

        jLabel4.setText("Password:");

        jLabel5.setText("Crear Cuenta");

        bguardar_cuenta.setText("Guardar");
        bguardar_cuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bguardar_cuentaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Crear_UsuariosLayout = new javax.swing.GroupLayout(Crear_Usuarios.getContentPane());
        Crear_Usuarios.getContentPane().setLayout(Crear_UsuariosLayout);
        Crear_UsuariosLayout.setHorizontalGroup(
            Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(tex_nombre_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tex_user_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tex_edad_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tex_password_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(bguardar_cuenta)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        Crear_UsuariosLayout.setVerticalGroup(
            Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_UsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tex_nombre_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tex_edad_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tex_user_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Crear_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tex_password_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(bguardar_cuenta)
                .addGap(38, 38, 38))
        );

        jLabel7.setText("Nombre");

        jLabel8.setText("Artista");

        jLabel9.setText("Canciones");

        jLabel10.setText("Duracion");

        jLabel11.setText("Genero");

        bguardar_cancion.setText("Guardar");
        bguardar_cancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bguardar_cancionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crear_CancionesLayout = new javax.swing.GroupLayout(crear_Canciones.getContentPane());
        crear_Canciones.getContentPane().setLayout(crear_CancionesLayout);
        crear_CancionesLayout.setHorizontalGroup(
            crear_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_CancionesLayout.createSequentialGroup()
                .addGroup(crear_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crear_CancionesLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crear_CancionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(crear_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(51, 51, 51)
                .addGroup(crear_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bguardar_cancion)
                    .addComponent(tex_genero_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tex_nombre_canciones, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tex_artistas_canciones, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tex_duracion_canciones, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        crear_CancionesLayout.setVerticalGroup(
            crear_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_CancionesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(crear_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tex_nombre_canciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(crear_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tex_artistas_canciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(crear_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tex_duracion_canciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(crear_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tex_genero_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bguardar_cancion)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel6.setText("Nombre de playlist");

        guardar_playlist.setText("Guardar Playlist");
        guardar_playlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardar_playlistMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Crear_PlaylistLayout = new javax.swing.GroupLayout(Crear_Playlist.getContentPane());
        Crear_Playlist.getContentPane().setLayout(Crear_PlaylistLayout);
        Crear_PlaylistLayout.setHorizontalGroup(
            Crear_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_PlaylistLayout.createSequentialGroup()
                .addGroup(Crear_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Crear_PlaylistLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(tex_nombreplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Crear_PlaylistLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(guardar_playlist)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        Crear_PlaylistLayout.setVerticalGroup(
            Crear_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_PlaylistLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(Crear_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tex_nombreplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(guardar_playlist)
                .addGap(83, 83, 83))
        );

        jLabel12.setText("Usuario");

        jLabel13.setText("Contraseña");

        biiniciar_sesion.setText("Ingresar");
        biiniciar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                biiniciar_sesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout iniciar_sesionLayout = new javax.swing.GroupLayout(iniciar_sesion.getContentPane());
        iniciar_sesion.getContentPane().setLayout(iniciar_sesionLayout);
        iniciar_sesionLayout.setHorizontalGroup(
            iniciar_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iniciar_sesionLayout.createSequentialGroup()
                .addGroup(iniciar_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(iniciar_sesionLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(iniciar_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(49, 49, 49)
                        .addGroup(iniciar_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tex_usuario_login, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(tex_clave_login)))
                    .addGroup(iniciar_sesionLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(biiniciar_sesion)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        iniciar_sesionLayout.setVerticalGroup(
            iniciar_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iniciar_sesionLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(iniciar_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tex_usuario_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(iniciar_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tex_clave_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(biiniciar_sesion)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel14.setText("Nombre:");

        jLabel15.setText("Artista:");

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Menu_crearalbumLayout = new javax.swing.GroupLayout(Menu_crearalbum.getContentPane());
        Menu_crearalbum.getContentPane().setLayout(Menu_crearalbumLayout);
        Menu_crearalbumLayout.setHorizontalGroup(
            Menu_crearalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_crearalbumLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(Menu_crearalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Menu_crearalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tex_artista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tex_nombrealbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Menu_crearalbumLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jButton1)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        Menu_crearalbumLayout.setVerticalGroup(
            Menu_crearalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_crearalbumLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(Menu_crearalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tex_nombrealbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Menu_crearalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Menu_crearalbumLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel15))
                    .addGroup(Menu_crearalbumLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(tex_artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(61, 61, 61))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Menu");

        menu_crearcuenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        menu_crearcuenta.setText("crear Usuarios");
        menu_crearcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_crearcuentaActionPerformed(evt);
            }
        });
        jMenu1.add(menu_crearcuenta);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Crear Abum");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menu_crearcancion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        menu_crearcancion.setText("Crear Cancion");
        menu_crearcancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_crearcancionActionPerformed(evt);
            }
        });
        jMenu1.add(menu_crearcancion);

        menu_crearplaylist.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_crearplaylist.setText("Crear Playlist");
        menu_crearplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_crearplaylistActionPerformed(evt);
            }
        });
        jMenu1.add(menu_crearplaylist);

        menu_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        menu_salir.setText("Salir");
        menu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_salirActionPerformed(evt);
            }
        });
        jMenu1.add(menu_salir);

        menu_iniciar_sesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        menu_iniciar_sesion.setText("Iniciar Sesion");
        menu_iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_iniciar_sesionActionPerformed(evt);
            }
        });
        jMenu1.add(menu_iniciar_sesion);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bguardar_cuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bguardar_cuentaMouseClicked

        String nombre_usuario;
        int edad;
        String username;
        String password;
        nombre_usuario = tex_nombre_cuenta.getText();
        edad = Integer.parseInt(tex_edad_cuenta.getText());
        username = tex_user_cuenta.getText();
        password = tex_password_cuenta.getText();
        Usuarios usuarios = new Usuarios(nombre_usuario, edad, username, password);
        L_usuarios.add(usuarios);

        agregar_archivob = new Aministrador_Usuarios("./Usuario.txt");
        agregar_archivob.cargarArchivo(); // Poner validación por si el archivo no existe.
        agregar_archivob.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Se agrego usuario");

        tex_nombre_cuenta.setText("");
        tex_edad_cuenta.setText("");
        tex_user_cuenta.setText("");
        tex_password_cuenta.setText("");

    }//GEN-LAST:event_bguardar_cuentaMouseClicked

    private void menu_crearcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_crearcuentaActionPerformed
        Crear_Usuarios.setModal(true);
        Crear_Usuarios.pack(); // sirve para acoplar el tamaño de la ventana a los elementos que contiene
        Crear_Usuarios.setLocationRelativeTo(this);
        Crear_Usuarios.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menu_crearcuentaActionPerformed

    private void menu_crearcancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_crearcancionActionPerformed
        crear_Canciones.setModal(true);
        crear_Canciones.pack(); // sirve para acoplar el tamaño de la ventana a los elementos que contiene
        crear_Canciones.setLocationRelativeTo(this);
        crear_Canciones.setVisible(true);         crear_Canciones.setVisible(true);         Crear_Usuarios.setVisible(true);       }//GEN-LAST:event_menu_crearcancionActionPerformed

    private void bguardar_cancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bguardar_cancionMouseClicked
        String Nombre_cancion = tex_nombre_canciones.getText();
        String Artista_cancion = tex_artistas_canciones.getText();
        int duracion = Integer.parseInt(tex_duracion_canciones.getText());
        L_canaciones.add(new Canciones(Nombre_cancion, Artista_cancion, duracion));
        JOptionPane.showMessageDialog(this, "Se agrego cancion");
        tex_nombre_canciones.setText("");
        tex_artistas_canciones.setText("");
        tex_duracion_canciones.setText("");
        tex_genero_cancion.setText("");
    }//GEN-LAST:event_bguardar_cancionMouseClicked

    private void guardar_playlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardar_playlistMouseClicked
        String nombre_playlist = tex_nombreplaylist.getText();
        tex_nombreplaylist.setText("");
        L_playlist.add(new Playlist(nombre_playlist));
    }//GEN-LAST:event_guardar_playlistMouseClicked

    private void menu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menu_salirActionPerformed

    private void menu_crearplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_crearplaylistActionPerformed
        Crear_Playlist.setVisible(true);
        Crear_Usuarios.setModal(true);
        Crear_Playlist.pack(); // sirve para acoplar el tamaño de la ventana a los elementos que contiene
        Crear_Playlist.setLocationRelativeTo(this);
// TODO add your handling code here:
    }//GEN-LAST:event_menu_crearplaylistActionPerformed

    private void menu_iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_iniciar_sesionActionPerformed
        iniciar_sesion.setVisible(true);
        iniciar_sesion.setModal(true);
        iniciar_sesion.pack(); // sirve para acoplar el tamaño de la ventana a los elementos que contiene
        iniciar_sesion.setLocationRelativeTo(this);

    }//GEN-LAST:event_menu_iniciar_sesionActionPerformed

    private void biiniciar_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biiniciar_sesionMouseClicked
        agregar_archivob = new Administrar_Usuarios("./Usuario.txt");
        agregar_archivob.cargarArchivo();
        L_usuarios = agregar_archivob.getListaUsuario();
        for (int i = 0; i < L_usuarios.size(); i++) {
            String password = ((Usuarios) L_usuarios.get(i)).getPassword();
            String userName = ((Usuarios) L_usuarios.get(i)).getNombre_usuario();
            if (tex_usuario_login.equals(userName) && tex_clave_login.getText().equals(password)) {
                JOptionPane.showMessageDialog(this, "Inicio sesion");
                emisor = L_usuarios.get(i);
            }

    }//GEN-LAST:event_biiniciar_sesionMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Menu_crearalbum.setVisible(true);
        Menu_crearalbum.setModal(true);
        Menu_crearalbum.pack(); // sirve para acoplar el tamaño de la ventana a los elementos que contiene
        Menu_crearalbum.setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String nombre = tex_nombrealbum.getText();
        String artista = tex_artista.getText();
        L_album.add(new Album(nombre, artista
        JOptionPane.showMessageDialog(this, "Secreo el album");
        tex_nombrealbum.setText("");
        tex_artista.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Crear_Playlist;
    private javax.swing.JDialog Crear_Usuarios;
    private javax.swing.JDialog Menu_crearalbum;
    private javax.swing.JButton bguardar_cancion;
    private javax.swing.JButton bguardar_cuenta;
    private javax.swing.JButton biiniciar_sesion;
    private javax.swing.JDialog crear_Canciones;
    private javax.swing.JButton guardar_playlist;
    private javax.swing.JDialog iniciar_sesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menu_crearcancion;
    private javax.swing.JMenuItem menu_crearcuenta;
    private javax.swing.JMenuItem menu_crearplaylist;
    private javax.swing.JMenuItem menu_iniciar_sesion;
    private javax.swing.JMenuItem menu_salir;
    private javax.swing.JTextField tex_artista;
    private javax.swing.JTextField tex_artistas_canciones;
    private javax.swing.JPasswordField tex_clave_login;
    private javax.swing.JTextField tex_duracion_canciones;
    private javax.swing.JTextField tex_edad_cuenta;
    private javax.swing.JTextField tex_genero_cancion;
    private javax.swing.JTextField tex_nombre_canciones;
    private javax.swing.JTextField tex_nombre_cuenta;
    private javax.swing.JTextField tex_nombrealbum;
    private javax.swing.JTextField tex_nombreplaylist;
    private javax.swing.JTextField tex_password_cuenta;
    private javax.swing.JTextField tex_user_cuenta;
    private javax.swing.JTextField tex_usuario_login;
    // End of variables declaration//GEN-END:variables
    ArrayList<Usuarios> L_usuarios = new ArrayList();
    ArrayList<Canciones> L_canaciones = new ArrayList();
    ArrayList L_playlist = new ArrayList();
    ArrayList L_album = new ArrayList();

    Aministrador_Usuarios agregar_archivob;
    Usuarios emisor;

}
